# Generated by Django 2.2.5 on 2019-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(verbose_name='date analyzed')),
                ('positive_tweets', models.IntegerField(default=0)),
                ('negative_tweets', models.IntegerField(default=0)),
                ('neutral_tweets', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
