# Generated by Django 2.2.5 on 2019-10-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PositivityIndex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PositivityIndex.User'),
        ),
    ]
