# Generated by Django 2.2.5 on 2019-10-03 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PositivityIndex', '0004_auto_20191002_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
