# Generated by Django 2.2.5 on 2019-10-03 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PositivityIndex', '0005_auto_20191002_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
